### ISSUE TITLE
Rows with duplicate records removed

### ISSUE THREAD

**Issue by stewmorg** [appeler/ethnicolr#91]
With simple set of data that include two records with the same last name, the resulting output only has one of those records included in the output file.

Input file contains

id,first_name,last_name
99956,Tony,Singh
99957,Toni,Singh

```
import pandas as pd
from ethnicolr import pred_census_ln

df = pd.read_csv(sys.argv[1])
print(df.shape) # prints 2 rows
df = pred_census_ln(df,"last_name")
print(df.shape) # prints 1 rows
```

The output of the script above has only one resulting row in the dataframe.

I believe the same behaviour is seen when calling other functions of the in the ethnicolr package.

**Comment by soodoku** [comment]
that's intended. you can left_join the output back to the df. otherwise we are predicting the same thing multiple times. (here the last name is the same and you are calling a last name pred method.)

**Comment by databurger** [comment]
"otherwise we are predicting the same thing multiple times." This is happening on the caller's machine. Why does API need to take care of this issue? If the caller hopes for an optimization, he should dedupe outside by himself. If the API wants to improve "batch" performance, it had better to recover the shape of the input data frame before return. Changing the shape of the input data frame silently isn't a good behavior.
